apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: vllm-test-june23 
  description: Secure Supply Chain Example for Chatbot Application   
  links:
    - url: https://www.redhat.com/en/solutions/trusted-software-supply-chain
      title: Trusted Secure Supply Chain 
      icon: dashboard
      type: admin-dashboard
  annotations:
    # ArgoCD apps from this template used rhtap-gitops as the grouping
    argocd/app-selector: rhtap/gitops=vllm-test-june23  
    janus-idp.io/tekton: vllm-test-june23 
    backstage.io/kubernetes-id: vllm-test-june23 
    backstage.io/techdocs-ref: dir:. 
    quay.io/repository-slug: jdubrick-ai/vllm-test-june23
  tags: ["ai", "llamacpp", "vllm", "python"] 
spec:
  type: service
  owner: user:guest 
  lifecycle: experimental
 